server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://172.20.0.100:8761/eureka/
spring:
  http:
    encoding:
      force: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.20.0.107:3306/crm?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
  application:
    name: marketing-management
#关闭安全验证
management:
  security:
    enabled: false
#打印sql语句
logging:
  level:
    com:
      shanyu:
        mapper: debug
