server:
  port: 10002
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/crm?charactorEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-provider

eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
  client:
    service-url:
      defaultZone: http://root:123456@localhost:9001/eureka

mybatis:
  type-aliases-package: cn.bdqn.crm.pojo
  mapper-locations: classpath:mapper/*Mapper.xml